name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  quality-gate:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/quality-gate.yml
    with:
      extended-tests: false
