name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  quality-gate:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/quality-gate.yml
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1857082304 }}
